on: [push, pull_request, workflow_dispatch]

jobs:
  test-drive:
    runs-on: ubuntu-latest
    name: test flutter package update
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.12.13+hotfix.5"
          channel: "stable"
      - name: run flutter package updater
        uses: ./
        with:
          flutter-project: "./labrat"
          git-email: "joshuaarus@gmail.com"
          git-name: "Joshua Arus"
          token: ${{ secrets.JOSHUAARUS_GITHUB_TOKEN }}
          log: "info"
